### ISSUE TITLE
Inconsistency between image and annotations while Zooming

### ISSUE THREAD

**Issue by Wiebke** [mlexchange/mlex_highres_segmentation#112]
When creating annotations with a relatively high drawing width, the zoom level of the annotations and the zoom level of the image seem to be slightly inconsistent.

See the two examples below, where I created a closed free form annotation close to the "border" of what I want to segmented while zoomed in, that crosses that border when zooming out. It seems like the size of the annotations changes in size to lesser degree in comparison to the image while zooming out.

![ZoomedIn](https://github.com/mlexchange/mlex_highres_segmentation/assets/391662/c3f42441-b458-41bb-a1fc-15aa1b1c5204)

![ZoomedOut](https://github.com/mlexchange/mlex_highres_segmentation/assets/391662/4c28430a-17b7-4b40-93a3-2a056590c96f)

**Comment by hannahker** [comment]
@Wiebke it seems that this is behaviour is happening due to how the SVG paths are rescaled at different zoom levels. This is implemented at a pretty low level in the plotly.js graphing library codebase (rather than in our application's Python code, ie.). 

How important is the ability to change the drawing width? We're wondering if this is actually redundant, given the "closed freeform" drawing mode? 

We're checking internally to explore options around: a) whether there are workarounds we could implement in Python, and b) whether a bugfix/feature could be added to plotly.js to address this. I'll note that changes at the plotly.js level can take some time (months) to be addressed. 

cc @danton267

**Comment by hannahker** [comment]
After discussion a decision was made to remove the freeform draw and line annotation modes, only giving the user the ability to draw closed shapes. This means that the line width control is no longer relevant, which also means that this issue is not present as shapes won't be drawn with thick line widths. See #125
